name: Node.js CI
permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@94196ee1d15439c1b6651cd87ef14e88ec435966
        with:
          node-version: 22.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - run: npm run test
